name: Java CI with Maven

on:
  pull_request:
    branches: [ "actions-test" ]
permissions: 
  contents: write
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: gh pr create --base main --head d4rkr0n1n-patch-1 --title "rollback-pr" --body "Rollback-Description"
